export type ThemeType = {
  text: string,
  // text2: string,
  // textFade: string,
  // textSecondary: string,
  // textSecondary2: string,
  // textSecondaryFade: string,
  bg: string,
  bg2: string,
  bg3: string,
  bgAlpha: string,
  bgSecondary: string,
  primary: string,
  hover: string,
  error: string,
};
